### ISSUE TITLE
Codeship Modulus Deploy Fails with Bower Components 

### ISSUE THREAD

**Issue by iamkevingreen** [iamkevingreen/Orion-Starter#1]
So despite modulus deploy working locally it doesn't work inside of codeship, I might try to set up CI to something like digital ocean or somewhere else to see if the same issue occurs... Not sure if it's an issue with demeteorizer or with the bower package that is supposed to build before the app is compiled.

**Comment by iamkevingreen** [comment]
removed codeship for now and no longer on modulus

**Comment by kmcurry** [comment]
November 2015: `modulus deploy` still frequently fails to ship Bower components on the first try. 2nd try always resolves it. Codeship is used in my web app, too.
